# Generated by Django 5.0.6 on 2024-09-25 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_city_shippingaddress_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shippingaddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.shippingaddress'),
        ),
    ]
