# Generated by Django 5.0.6 on 2024-09-25 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='shippingaddress',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='orderitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.orderitem'),
        ),
    ]
