# Generated by Django 5.0.6 on 2024-09-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_payment_vnpay'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_vnpay',
            name='vnp_ResponseCode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment_vnpay',
            name='vnp_TransactionNo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
