# Generated by Django 5.0.6 on 2024-11-03 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
