# Generated by Django 5.0.6 on 2024-11-03 16:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_category_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date_added',
        ),
        migrations.AddField(
            model_name='product',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
