# Generated by Django 5.0.6 on 2024-11-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_category_date_added_product_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='origin_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
