# Generated by Django 5.0.6 on 2024-11-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='input_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
