# Generated by Django 5.0.6 on 2024-11-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Danh mục sản phẩm', 'verbose_name_plural': 'Danh mục sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Mặt hàng trong đơn', 'verbose_name_plural': 'Mặt hàng trong đơn'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name': 'Địa chỉ giao hàng', 'verbose_name_plural': 'Địa chỉ giao hàng'},
        ),
        migrations.AddField(
            model_name='product',
            name='hot',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
